apiVersion: apps/v1
kind: Deployment
metadata:
  name: zealous
spec:
  selector:
    matchLabels:
      app: zealous
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: zealous
    spec:
      containers:
      - name: zealous
        image: tanveer941/zealous
        ports:
        - containerPort: 5000
